cmake_minimum_required(VERSION 3.28)
project(design_patterns)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(singleton_pattern)
add_subdirectory(factory_pattern)
add_subdirectory(factory_pattern_abstract)
add_subdirectory(builder_pattern)
add_subdirectory(prototype_pattern)
add_subdirectory(adapter_pattern)
add_subdirectory(proxy_pattern)
add_subdirectory(decorator_pattern)
add_subdirectory(facade_pattern)
add_subdirectory(bridge_pattern)
add_subdirectory(composite_pattern)
add_subdirectory(flyweight_pattern)
add_subdirectory(observer_pattern)
add_subdirectory(strategy_pattern)
add_subdirectory(command_pattern)
add_subdirectory(mediator_pattern)
add_subdirectory(memento_pattern)
add_subdirectory(template_method_pattern)
add_subdirectory(iterator_pattern)
add_subdirectory(state_pattern)
add_subdirectory(chain_of_responsibility_pattern)